import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import style from "./page.module.scss";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={style.container}>
          <Sidebar />
          <div className={style.mainContent}>
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
